.PHONY: compile clean run measure make_dirs copy_filescd

compile: | make_dirs copy_files
	
clean:
	rm -r python2.6
	rm -r python2.7
	rm -r python3.0
	rm -r python3.4
	rm -r python3.5
	rm -r python3.6
	rm -r python3.7
	rm -r python3.8
	rm -r python3.9
	rm -r python3.10
	rm -r python3.11 

run:
	-python2.6 ./python2.6/spectralnorm-8.py 21
	-python2.7 ./python2.7/spectralnorm-8.py 21
	-python3.0 ./python3.0/spectralnorm-8.py 21
	-python3.4 ./python3.4/spectralnorm-8.py 21
	-python3.5 ./python3.5/spectralnorm-8.py 21
	-python3.6 ./python3.6/spectralnorm-8.py 21
	-python3.7 ./python3.7/spectralnorm-8.py 21
	-python3.8 ./python3.8/spectralnorm-8.py 21
	-python3.9 ./python3.9/spectralnorm-8.py 21
	-python3.10 ./python3.10/spectralnorm-8.py 21
	-python3.11 ./python3.11/spectralnorm-8.py 21
	

measure:


make_dirs:
	mkdir -p python2.6
	mkdir -p python2.7
	mkdir -p python3.0
	mkdir -p python3.4
	mkdir -p python3.5
	mkdir -p python3.6
	mkdir -p python3.7
	mkdir -p python3.8
	mkdir -p python3.9
	mkdir -p python3.10
	mkdir -p python3.11 

copy_files:
	sudo cp spectralnorm-8.py ./python2.6/spectralnorm-8.py
	sudo cp spectralnorm-8.py ./python2.7/spectralnorm-8.py
	sudo cp spectralnorm-8.py ./python3.0/spectralnorm-8.py
	sudo cp spectralnorm-8.py ./python3.4/spectralnorm-8.py
	sudo cp spectralnorm-8.py ./python3.5/spectralnorm-8.py
	sudo cp spectralnorm-8.py ./python3.6/spectralnorm-8.py
	sudo cp spectralnorm-8.py ./python3.7/spectralnorm-8.py
	sudo cp spectralnorm-8.py ./python3.8/spectralnorm-8.py
	sudo cp spectralnorm-8.py ./python3.9/spectralnorm-8.py
	sudo cp spectralnorm-8.py ./python3.10/spectralnorm-8.py
	sudo cp spectralnorm-8.py ./python3.11/spectralnorm-8.py 