.PHONY: compile clean run measure make_dirs copy_filescd

CLang34 := $(DISS_C)/clang-3.4.2/bin/
CLang35 := $(DISS_C)/clang-3.5.2/bin/
CLang36 := $(DISS_C)/clang-3.6.2/bin/
CLang37 := $(DISS_C)/clang-3.7.1/bin/
CLang38 := $(DISS_C)/clang-3.8.1/bin/
CLang4 := $(DISS_C)/clang-4.0.0/bin/
CLang5 := $(DISS_C)/clang-5.0.2/bin/
CLang6 := $(DISS_C)/clang-6.0.1/bin/
CLang7 := $(DISS_C)/clang-7.0.1/bin/
CLang8 := $(DISS_C)/clang-8.0.0/bin/
CLang9 := $(DISS_C)/clang-9.0.0/bin/
CLang10 := $(DISS_C)/clang-10.0.0/bin/
CLang11 := $(DISS_C)/clang-11.1.0/bin/
CLang12 := $(DISS_C)/clang-12.0.1/bin/
CLang13 := $(DISS_C)/clang-13.0.1/bin/
CLang14 := $(DISS_C)/clang-14.0.0/bin/
CLang15 := $(DISS_C)/clang-15.0.6/bin/

IncCLang34 := $(DISS_C)/clang-3.4.2/include/c++/v1
IncCLang35 := $(DISS_C)/clang-3.5.2/include/c++/v1
IncCLang36 := $(DISS_C)/clang-3.6.2/include/c++/v1
IncCLang37 := $(DISS_C)/clang-3.7.1/include/c++/v1
IncCLang38 := $(DISS_C)/clang-3.8.1/include/c++/v1
IncCLang4 := $(DISS_C)/clang-4.0.0/include/c++/v1
IncCLang5 := $(DISS_C)/clang-5.0.2/include/c++/v1
IncCLang6 := $(DISS_C)/clang-6.0.1/include/c++/v1
IncCLang7 := $(DISS_C)/clang-7.0.1/include/c++/v1
IncCLang8 := $(DISS_C)/clang-8.0.0/include/c++/v1
IncCLang9 := $(DISS_C)/clang-9.0.0/include/c++/v1
IncCLang10 := $(DISS_C)/clang-10.0.0/include/c++/v1
IncCLang11 := $(DISS_C)/clang-11.1.0/include/c++/v1
IncCLang12 := $(DISS_C)/clang-12.0.1/include/c++/v1
IncCLang13 := $(DISS_C)/clang-13.0.1/include/c++/v1
IncCLang14 := $(DISS_C)/clang-14.0.0/include/c++/v1
IncCLang15 := $(DISS_C)/clang-15.0.6/include/c++/v1


compile: | make_dirs copy_files
	
clean:
	rm -r -f clang-3.4
	rm -r -f clang-3.5
	rm -r -f clang-3.6
	rm -r -f clang-3.7
	rm -r -f clang-3.8
	rm -r -f clang-4.0
	rm -r -f clang-5.0
	rm -r -f clang-6.0
	rm -r -f clang-7.0
	rm -r -f clang-8.0
	rm -r -f clang-9.0
	rm -r -f clang-10.0
	rm -r -f clang-11.1
	rm -r -f clang-12.0
	rm -r -f clang-13.0
	rm -r -f clang-14.0
	rm -r -f clang-15.0

run:
	./clang-3.4/knucleotide 21
	./clang-3.5/knucleotide 21
	./clang-3.6/knucleotide 21
	./clang-3.7/knucleotide 21
	./clang-3.8/knucleotide 21
	./clang-4.0/knucleotide 21
	./clang-5.0/knucleotide 21
	./clang-6.0/knucleotide 21
	./clang-7.0/knucleotide 21
	./clang-8.0/knucleotide 21
	./clang-9.0/knucleotide 21
	./clang-10.0/knucleotide 21
	./clang-11.1/knucleotide 21
	./clang-12.0/knucleotide 21
	./clang-13.0/knucleotide 21
	./clang-14.0/knucleotide 21
	./clang-15.0/knucleotide 21

	

measure:
#	python3 ../../main.py "./clang-3.4/binarytrees-8 21" "./clang-3.4" "cpp-bintrees-3.4" 40 45 0.01 -r 10
#	python3 ../../main.py "./clang-3.5/binarytrees-8 21" "./clang-3.5" "cpp-bintrees-3.5" 40 45 0.01 -r 10
#	python3 ../../main.py "./clang-3.6/binarytrees-8 21" "./clang-3.6" "cpp-bintrees-3.6" 40 45 0.01 -r 10
#	python3 ../../main.py "./clang-3.7/binarytrees-8 21" "./clang-3.7" "cpp-bintrees-3.7" 40 45 0.01 -r 10
#	python3 ../../main.py "./clang-3.8/binarytrees-8 21" "./clang-3.8" "cpp-bintrees-3.8" 40 45 0.01 -r 10
#	python3 ../../main.py "./clang-4.0/binarytrees-8 21" "./clang-4.0" "cpp-bintrees-4.0" 40 45 0.01 -r 10
#	python3 ../../main.py "./clang-5.0/binarytrees-8 21" "./clang-5.0" "cpp-bintrees-5.0" 40 45 0.01 -r 10
#	python3 ../../main.py "./clang-6.0/binarytrees-8 21" "./clang-6.0" "cpp-bintrees-6.0" 40 45 0.01 -r 10
#	python3 ../../main.py "./clang-7.0/binarytrees-8 21" "./clang-7.0" "cpp-bintrees-7.0" 40 45 0.01 -r 10
#	python3 ../../main.py "./clang-8.0/binarytrees-8 21" "./clang-8.0" "cpp-bintrees-8.0" 40 45 0.01 -r 10
#	python3 ../../main.py "./clang-9.0/binarytrees-8 21" "./clang-9.0" "cpp-bintrees-9.0" 40 45 0.01 -r 10
#	python3 ../../main.py "./clang-10.0/binarytrees-8 21" "./clang-10.0" "cpp-bintrees-10.0" 40 45 0.01 -r 10
#	python3 ../../main.py "./clang-11.1/binarytrees-8 21" "./clang-11.1" "cpp-bintrees-11.1" 40 45 0.01 -r 10
#	python3 ../../main.py "./clang-12.0/binarytrees-8 21" "./clang-12.0" "cpp-bintrees-12.0" 40 45 0.01 -r 10
#	python3 ../../main.py "./clang-13.0/binarytrees-8 21" "./clang-13.0" "cpp-bintrees-13.0" 40 45 0.01 -r 10
#	python3 ../../main.py "./clang-14.0/binarytrees-8 21" "./clang-14.0" "cpp-bintrees-14.0" 40 45 0.01 -r 10
#	python3 ../../main.py "./clang-15.0/binarytrees-8 21" "./clang-15.0" "cpp-bintrees-15.0" 40 45 0.01 -r 10




make_dirs:
	mkdir -p clang-3.4
	mkdir -p clang-3.5
	mkdir -p clang-3.6
	mkdir -p clang-3.7
	mkdir -p clang-3.8
	mkdir -p clang-4.0
	mkdir -p clang-5.0
	mkdir -p clang-6.0
	mkdir -p clang-7.0
	mkdir -p clang-8.0
	mkdir -p clang-9.0
	mkdir -p clang-10.0
	mkdir -p clang-11.1
	mkdir -p clang-12.0
	mkdir -p clang-13.0
	mkdir -p clang-14.0
	mkdir -p clang-15.0

copy_files:
#	$(CLang34)clang++ -pipe -O3 -std=c++14 -fomit-frame-pointer -march=native -I$(IncCLang34) knucleotide.cpp -o ./clang-3.4/knucleotide -stdlib=libstdc++
#	$(CLang35)clang++ -pipe -O3 -std=c++14 -fomit-frame-pointer -march=native -I$(IncCLang35) knucleotide.cpp -o ./clang-3.5/knucleotide -stdlib=libstdc++
#	$(CLang36)clang++ -pipe -O3 -std=c++14 -fomit-frame-pointer -march=native -I$(IncCLang36) knucleotide.cpp -o ./clang-3.6/knucleotide -stdlib=libstdc++
#	$(CLang37)clang++ -pipe -O3 -std=c++14 -fomit-frame-pointer -march=native -I$(IncCLang37) knucleotide.cpp -o ./clang-3.7/knucleotide -stdlib=libstdc++
#	$(CLang38)clang++ -pipe -O3 -std=c++14 -fomit-frame-pointer -march=native -I$(IncCLang38) knucleotide.cpp -o ./clang-3.8/knucleotide -stdlib=libstdc++
#	$(CLang4)clang++ -pipe -O3 -std=c++14 -fomit-frame-pointer -march=native -I$(IncCLang4) knucleotide.cpp -o ./clang-4.0/knucleotide -stdlib=libstdc++
#	$(CLang5)clang++ -pipe -O3 -std=c++14 -fomit-frame-pointer -march=native -I$(IncCLang5) knucleotide.cpp -o ./clang-5.0/knucleotide -stdlib=libstdc++
#	$(CLang6)clang++ -pipe -O3 -std=c++14 -fomit-frame-pointer -march=native -I$(IncCLang6) knucleotide.cpp -o ./clang-6.0/knucleotide -stdlib=libstdc++
#	$(CLang7)clang++ -pipe -O3 -std=c++14 -fomit-frame-pointer -march=native -I$(IncCLang7) knucleotide.cpp -o ./clang-7.0/knucleotide -stdlib=libstdc++
#	$(CLang8)clang++ -pipe -O3 -std=c++14 -fomit-frame-pointer -march=native -I$(IncCLang8) knucleotide.cpp -o ./clang-8.0/knucleotide -stdlib=libstdc++
#	$(CLang9)clang++ -pipe -O3 -std=c++14 -fomit-frame-pointer -march=native -I$(IncCLang9) knucleotide.cpp -o ./clang-9.0/knucleotide -stdlib=libstdc++
#	$(CLang10)clang++ -pipe -O3 -std=c++14 -fomit-frame-pointer -march=native -I$(IncCLang10) knucleotide.cpp -o ./clang-10.0/knucleotide -stdlib=libstdc++
#	$(CLang11)clang++ -pipe -O3 -std=c++14 -fomit-frame-pointer -march=native -I$(IncCLang11) knucleotide.cpp -o ./clang-11.1/knucleotide -stdlib=libstdc++
#	$(CLang12)clang++ -pipe -O3 -std=c++14 -fomit-frame-pointer -march=native -I$(IncCLang12) knucleotide.cpp -o ./clang-12.0/knucleotide -stdlib=libstdc++
#	$(CLang13)clang++ -pipe -O3 -std=c++14 -fomit-frame-pointer -march=native -I$(IncCLang13) knucleotide.cpp -o ./clang-13.0/knucleotide -stdlib=libstdc++
#	$(CLang14)clang++ -pipe -O3 -std=c++14 -fomit-frame-pointer -march=native -I$(IncCLang14) knucleotide.cpp -o ./clang-14.0/knucleotide -stdlib=libstdc++
#	$(CLang15)clang++ -pipe -O3 -std=c++14 -fomit-frame-pointer -march=native -I$(IncCLang15) knucleotide.cpp -o ./clang-15.0/knucleotide -stdlib=libstdc++
	